logging:
  path: ./logs/zuihou-gateway-server
  file: ${logging.path}/root.log
  common-pattern: '%d{yyyy-MM-dd HH:mm:ss.SSS}:[%5p] [%t:%r] [%C{1}:%M:%L] --> %m%n'
  level:
    console: INFO
    filter: INFO


server:
  port: 9770 #启动端口

# eureka实例的状态页面和健康监控默认为/info和/health，这是spring boot actuator提供的默认终端点。当应用不使用默认的上下文(context path或servlet path，比如配置server.servletPath=/test），或者管理zhongduan路径（比如配置management.contextPath=/admin）。
eureka:
  instance:
#    status-page-url-path: ${management.context-path}/info
#    health-check-url-path: ${management.context-path}/health
    preferIpAddress: true
    metadata-map:
      user.name: ${security.user.name}
      user.password: ${security.user.password}
      management.context-path: ${management.context-path}

spring:
  profiles:
    active: dev
  application:
    name: zuihou-gateway-server
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  rabbitmq:
    host: zuihou.rabbitmq.host
    port: 5672
    password: guest
    username: guest
  redis:
    host: zuihou.redis.host
    port: 6379
    pool:
      max-active: 20
      min-idle: 2
      max-idle: 8
      max-wait: 100
    key-prefix: dev
  sleuth:
    sampler:
      percentage: 1
    integration:
      enabled: false
    scheduled:
      skip-pattern: "^org.*HystrixStreamTask$"
  zipkin:
    base-url: http://zuihou-zipkin:8510
    locator:
      discovery:
        enabled: true
    service:
      name: ${spring.application.name}
    rabbitmq:
      queue: zipkin

management:
  security:
    enabled: true
  context-path: /mgmt

security:
  basic:
    enabled: true
    path: ${management.context-path}
  user:
    name: admin
    password: ${SECURITY_USER_PASSWORD:admin}
endpoints:
  health:
    enabled: true
    sensitive: true  #actuator的health接口是否需要安全保证

zuul:
  ignored-services: "*"   # 忽略eureka上的所有服务
  sensitive-headers:      # 一些比较敏感的请求头，不想通过zuul传递过去， 可以通过该属性进行设置
  prefix: /api #为zuul设置一个公共的前缀
  ratelimit: # 网关限流
    key-prefix: gateway_rate
    enabled: false
    repository: REDIS #REDIS, JPA, IN_MEMORY
    behind-proxy: true
    default-policy: # optional - will apply unless specific policy exists
      limit: 10
      refresh-interval: 60 #default value (in seconds)
      type: #optional
        - user
        - origin
        - url
  routes:  # 路由配置方式
    base:  # 其中 back 是路由名称，可以随便定义，但是path和service-id需要一一对应
      path: /base/**
      serviceId: zuihou-base-server
    admin:  # 其中 admin 是路由名称，可以随便定义，但是path和service-id需要一一对应
      path: /admin/**
      serviceId: zuihou-admin-server
    auth:    # 其中 auth 是路由名称，可以随便定义，但是path和service-id需要一一对应
      path: /auth/**
      serviceId: zuihou-auth-server
    file:
      path: /file/**
      serviceId: zuihou-file-server
    mail:
      path: /mail/**
      serviceId: zuihou-mail-server
    sms:
      path: /sms/**
      serviceId: zuihou-sms-server

# 网关忽略拦截前缀（自定义）
gateway:
  ignore:
    start-with-list:
      - /static
      - /auth/app
      - /auth/client
      - /base/swagger-ui.html
      - /base/webjars
      - /base/v2/api-docs
      - /base/swagger-resources
      - /admin/swagger-ui.html
      - /admin/webjars
      - /admin/v2/api-docs
      - /admin/swagger-resources

#请求和响应GZIP压缩支持
feign:
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true

ribbon:
  eureka:
    enabled: true
  ReadTimeout: 60000
  ConnectTimeout: 60000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: false


hystrix:
  threadpool:
    default:
      coreSize: 1000 # #并发执行的最大线程数，默认10
      maxQueueSize: 1000 # #BlockingQueue的最大队列数
      queueSizeRejectionThreshold: 500 # #即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 50000

auth:
  serviceId: zuihou-auth-server
  app:
    token-header: token # 其三方应用token
    pub-key:  # 服务端公钥路径
      path: app/pub.key
  client:
    id: zuihou-gateway-server  #不填则默认读取spring.application.name
    secret: 123456
    token-header: client-token
    admin-header: _isAdmin
    pub-key: # 客服端公钥路径
      path: client/pub.key

