zuihou:
  ip:
    mysql: ${MYSQL_IP:127.0.0.1}
    nginx: ${NGINX_IP:127.0.0.1}
    executor: ${EXECUTOR_IP:127.0.0.1}
  mysql:
    authority:
      database: zuihou_authority_dev
      host: ${zuihou.ip.mysql}
      port: ${zuihou.mysql.port}
    msgs:
      database: zuihou_msgs_dev
      host: ${zuihou.ip.mysql}
      port: ${zuihou.mysql.port}
    jobs:
      database: zuihou_jobs_dev
      host: ${zuihou.ip.mysql}
      port: ${zuihou.mysql.port}
    username: root
    password: root
    port: 3306
    driverClassName: com.mysql.cj.jdbc.Driver
### xxl-job email
xxl.job:
  mail:
    host: smtp.163.com
    port: 25
    ssl: false
    username: ovono802302@163.com
    password: asdfzxcv
    sendNick: 《任务调度平台ZUIHOU-JOB》
  login:
    username: zuihou
    password: zuihou
  accessToken:
  i18n:
  # 以下是client 执行器端配置（注意：若不想配置调度器也是执行器，请自行参考xxl）
  admin:
    addresses: http://127.0.0.1:${server.port}/${spring.application.name}
  executor:
    appname: ${spring.application.name}
    ip: ${zuihou.ip.executor}
    port: ${zuihou.port.executor:8771}
    logpath: /projects/logs/${spring.application.name}/
    logretentiondays: -1


logging:
  path: /projects/logs/${spring.application.name}

server:
  servlet:
    context-path: /${spring.application.name}
  port: 8767
  undertow: # jetty  undertow
    io-threads: 4 # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
    worker-threads: 80  # 阻塞任务线程池, 当执行类似servlet请求阻塞操作, undertow会从这个线程池中取得线程,它的值设置取决于系统的负载
    buffer-size: 1024  # 以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理 , 每块buffer的空间大小,越小的空间被利用越充分
    direct-buffers: true  # 是否分配的直接内存

mybatis:
  mapper-locations: classpath:mybatis-mapper/*.xml

spring:
  application:
    name: zuihou-jobs-server
  profiles:
    active: dev
  datasource:
    druid:
      jobs:
        url: jdbc:mysql://${zuihou.mysql.jobs.host}:${zuihou.mysql.jobs.port}/${zuihou.mysql.jobs.database}?serverTimezone=CTT&characterEncoding=utf8&useUnicode=true&useSSL=false
        username: ${zuihou.mysql.username}
        password: ${zuihou.mysql.password}
        driver-class-name: ${zuihou.mysql.driverClassName}
      authority:
        username: ${zuihou.mysql.username}
        password: ${zuihou.mysql.password}
        driver-class-name: ${zuihou.mysql.driverClassName}
        url: jdbc:mysql://${zuihou.mysql.authority.host}:${zuihou.mysql.authority.port}/${zuihou.mysql.authority.database}?serverTimezone=CTT&characterEncoding=utf8&useUnicode=true&useSSL=false
        initialSize: 10
        minIdle: 50
        maxActive: 200
      msgs:
        username: ${zuihou.mysql.username}
        password: ${zuihou.mysql.password}
        driver-class-name: ${zuihou.mysql.driverClassName}
        url: jdbc:mysql://${zuihou.mysql.msgs.host}:${zuihou.mysql.msgs.port}/${zuihou.mysql.msgs.database}?serverTimezone=CTT&characterEncoding=utf8&useUnicode=true&useSSL=false
        initialSize: 10
        minIdle: 50
        maxActive: 200
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static/
  freemarker:
    templateLoaderPath: classpath:/templates/
    suffix: .ftl
    charset: UTF-8
    request-context-attribute: request
    settings:
      number_format: 0.##       #解決freemarker数字输出中的逗号问题
      #      classic_compatible: true  #默认情况变量为null则替换为空字符串，如果需要自定义，写上${empty!"EmptyValue of fbysss"}的形式即可
      whitespace_stripping: true      # 剥离前后空字符串
      boolean_format: true,false      # 布尔类型格式化
      datetime_format: yyyy-MM-dd HH:mm:ss  # dateTime 类型格式化， 使用日期类型时， 需要在参数后追加 ?datetime eg: ${date?datetime}
      date_format: yyyy-MM-dd   # date 类型格式化， 使用日期类型时， 需要在参数后追加 ?date eg: ${date?date}
      time_format: HH:mm:ss      # time 类型格式化， 使用日期类型时， 需要在参数后追加 ?time eg: ${date?time}
      template_exception_handler: ignore   # 忽略模版异常
      default_encoding: UTF-8      # 默认编码
      url_escaping_charset: UTF-8  # url 转义编码
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true


mybatis-plus:
  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
  mapper-locations:
    - classpath:mybatis-mapper/**/*Mapper.xml
    - classpath:mapper_authority/**/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.xxl.job.admin.core.model,com.github.zuihou.authority.entity
  global-config:
    db-config:
      #    super-mapper-class: com.zuihousoft.db.MyBaseMapper
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: INPUT
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: NOT_EMPTY
      #驼峰下划线转换
      #      db-column-underline: true
      #mp2.3+ 全局表前缀 mp_
      #table-prefix: mp_
      #刷新mapper 调试神器
      #      refresh-mapper: true
      #数据库大写下划线转换
      #capital-mode: true
      #逻辑删除配置（下面3个配置）
      logic-delete-value: 4
      logic-not-delete-value: 0
  configuration:
    #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
    map-underscore-to-camel-case: true
    cache-enabled: false
    #配置JdbcTypeForNull, oracle数据库必须配置
    jdbc-type-for-null: 'null'

