management:
  security:
    enabled: true
    roles: SUPERUSER
  context-path: /mgmt
security:
  basic:
    enabled: true
    path: ${management.context-path}
  user:
    name: admin
    password: ${SECURITY_USER_PASSWORD:admin}
endpoints:
  health:
    enabled: true
    sensitive: true  # actuator的health接口是否需要安全保证

logging:
  path: ./logs/zuihou-monitor
  file: ${logging.path}/root.log
  common-pattern: '%d{yyyy-MM-dd HH:mm:ss.SSS}:[%5p] [%t:%r] [%C{1}:%M:%L] --> %m%n'
  level:
    org.springframework.cloud.netflix.zuul.filters.post.SendErrorFilter: error
    console: INFO

server:
  port: 8515

turbine:
  stream:
    port: 8516

eureka:
  instance:
#    status-page-url-path: ${management.context-path}/info
#    health-check-url-path: ${management.context-path}/health
    prefer-ip-address: true
    metadata-map:
      user.name: ${security.user.name}
      user.password: ${security.user.password}
      management.context-path: ${management.context-path}

spring:
#  mail:
#    host: smtp.163.com
#    username: aaa@163.com
#    password: aaa
#    properties:
#      smtp:
#        auth: true
#        starttls:
#          enable: true
#          required: true
  rabbitmq:
    host: zuihou.rabbitmq.host # 在hosts文件中配置地址
    port: 5672
    username: guest
    password: guest
  boot:
    admin:
      routes:
        endpoints: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream
      turbine:
        clusters: default
        location: http://monitor.zuihou.com:${turbine.stream.port}
#      context-path: ${management.context-path}
#      notify:      # 加了通知后，spring-boot-admin 通过/health验证当前项目是否
#        mail:
#          to: aaa@qq.com
#          from: xxx@163.com
#          ignore-changes: UNKNOWN:UP
