server:
  port: 8507

eureka:
  instance:
#    status-page-url-path: ${management.context-path}/info
#    health-check-url-path: ${management.context-path}/health
#    prefer-ip-address: true
#    hostname: ${eureka.hostname:eureka.zuihou.com}    # 指定该Eureka实例的主机名
    metadata-map:
      user.name: ${security.user.name}
      user.password: ${security.user.password}
      management.context-path: ${management.context-path}
  client:
    service-url:
      defaultZone: http://${prod1.eureka.hostname}:${prod1.eureka.server.port}/eureka/,http://${prod2.eureka.hostname}:${prod2.eureka.server.port}/eureka/
