logging:
  path: ./logs/zuihou-zipkin
  file: ${logging.path}/root.log
  common-pattern: '%d{yyyy-MM-dd HH:mm:ss.SSS}:[%5p] [%t:%r] [%C{1}:%M:%L] --> %m%n'
  level:
    console: INFO

spring:
  profiles:
    active: dev
  application:
    name: zuihou-zipkin
  sleuth:
    enabled: false # 表示当前程序不使用sleuth
#  rabbitmq:
#    host: zuihou.rabbitmq.host # 在hosts文件中配置地址
#    port: 5672
#    username: guest
#    password: guest
  datasource:
    schema[0]: classpath:/zipkin.sql #数据库脚本创建地址，当有多个是可使用[x]表示集合第几个元素
    #spring boot数据源配置
    url: jdbc:mysql://zuihou.mysql.host:3306/zuihou_zipkin_dev?serverTimezone=CTT&characterEncoding=utf8&useUnicode=true&useSSL=false
    username: root
    password: root     # 这里不需要加密
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialize: true
    continue-on-error: true

# 表示zipkin数据存储方式是mysql
zipkin:
  storage:
    type: mysql
  collector:
    http:
      enabled: true  # 这里开启了http模式，不确定是走rabbitmq，还是http 进行监控的
    rabbitmq:
      addresses: zuihou.rabbitmq.host:5672
      username: guest
      password: guest
      queue: zipkin

server:
  port: 8510

eureka:
  instance:
#    status-page-url-path: ${management.context-path}/info
#    health-check-url-path: ${management.context-path}/health
    preferIpAddress: true
    metadata-map:
      user.name: ${security.user.name}
      user.password: ${security.user.password}
      management.context-path: ${management.context-path}

management:
  security:
    enabled: true
    roles: SUPERUSER
  context-path: /mgmt

security:
  basic:
    enabled: true
    path: ${management.context-path}
  user:
    name: admin
    password: ${SECURITY_USER_PASSWORD:admin}
endpoints:
  health:
    enabled: true
    sensitive: true  #actuator的health接口是否需要安全保证
